package io.beatmaps.common.schema

import io.beatmaps.common.OptionalProperty
import io.beatmaps.common.beatsaber.BSFxEventsCollection
import io.beatmaps.common.beatsaber.BSVfxEventBoxGroup
import io.beatmaps.common.beatsaber.NodeNotPresent
import io.beatmaps.common.beatsaber.NodePresent
import io.beatmaps.common.schema.SchemaCommon.validateFolder
import org.junit.Test
import org.valiktor.DefaultConstraintViolation
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull

class SchemaTest33 {
    @Test
    fun schema3_2as3_3() {
        val ex = validateFolder("3_2as3_3")
        assertNotNull(ex)

        assertEquals(2, ex.constraintViolations.size)
        assertEquals(
            setOf(
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.vfxEventBoxGroups",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`._fxEventsCollection",
                    OptionalProperty.NotPresent,
                    NodePresent
                )
            ),
            ex.constraintViolations
        )
    }

    @Test
    fun schema3_3() {
        val ex = validateFolder("3_3")
        assertNull(ex)
    }

    @Test
    fun schema3_3as3_2() {
        val ex = validateFolder("3_3as3_2")
        assertNotNull(ex)

        assertEquals(125, ex.constraintViolations.size)
        assertEquals(
            setOf(
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.bpmEvents[0].beat",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[0]._time",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[0].y",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[0].angleOffset",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[1].color",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[1].y",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[1].angleOffset",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[2].y",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[2].angleOffset",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[4].color",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[4].x",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[4].y",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[4].angleOffset",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[5].color",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[5].direction",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[5].x",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[5].y",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[5].angleOffset",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorNotes[6].angleOffset",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.bombNotes[0].beat",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.bombNotes[0].x",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.bombNotes[0].y",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.bombNotes[1].x",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.bombNotes[1].y",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.obstacles[0].x",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.obstacles[0].y",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.obstacles[1].y",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.sliders[0].color",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.sliders[0].x",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.sliders[0].y",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.sliders[0].tailX",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.sliders[0].tailY",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.sliders[0].tailCutDirection",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.sliders[0].sliderMidAnchorMode",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.burstSliders[0].tailX",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.burstSliders[0].tailY",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[0].beat",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[1].beat",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[1].value",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[3].value",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[6].value",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[9].value",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[9].floatValue",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[10].value",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[10].floatValue",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[11].floatValue",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[12].floatValue",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.basicBeatmapEvents[13].floatValue",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorBoostBeatmapEvents[0].beat",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorBoostBeatmapEvents[0].boost",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorBoostBeatmapEvents[2].boost",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.colorBoostBeatmapEvents[4].boost",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].beat",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].indexFilter.param0",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].indexFilter.param1",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].indexFilter.reversed",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].indexFilter.chunks",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].indexFilter.randomType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].indexFilter.seed",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].indexFilter.limit",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].indexFilter.alsoAffectsType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].beatDistributionParam",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].brightnessDistributionParam",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].brightnessDistributionShouldAffectFirstBaseEvent",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].lightColorBaseDataList[0].beat",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].lightColorBaseDataList[0].transitionType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[0].lightColorBaseDataList[0].strobeFrequency",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].indexFilter.param1",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].indexFilter.reversed",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].indexFilter.chunks",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].indexFilter.randomType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].indexFilter.seed",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].indexFilter.limit",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].indexFilter.alsoAffectsType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].beatDistributionParam",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].brightnessDistributionParam",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].brightnessDistributionShouldAffectFirstBaseEvent",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].lightColorBaseDataList[0].transitionType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].lightColorBaseDataList[0].strobeFrequency",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].lightColorBaseDataList[1].transitionType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].lightColorBaseDataList[1].brightness",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[1].lightColorBaseDataList[1].strobeFrequency",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].indexFilter.param1",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].indexFilter.reversed",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].indexFilter.chunks",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].indexFilter.randomType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].indexFilter.seed",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].indexFilter.limit",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].indexFilter.alsoAffectsType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].beatDistributionParam",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].brightnessDistributionParam",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].brightnessDistributionShouldAffectFirstBaseEvent",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].lightColorBaseDataList[0].transitionType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].lightColorBaseDataList[0].strobeFrequency",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[2].lightColorBaseDataList[1].strobeFrequency",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].indexFilter.param1",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].indexFilter.reversed",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].indexFilter.chunks",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].indexFilter.randomType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].indexFilter.seed",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].indexFilter.limit",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].indexFilter.alsoAffectsType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].beatDistributionParam",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].brightnessDistributionParam",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].brightnessDistributionShouldAffectFirstBaseEvent",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].lightColorBaseDataList[0].transitionType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightColorEventBoxGroups[0].eventBoxes[3].lightColorBaseDataList[0].strobeFrequency",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].indexFilter.param1",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].indexFilter.reversed",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].indexFilter.chunks",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].indexFilter.randomType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].indexFilter.seed",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].indexFilter.limit",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].indexFilter.alsoAffectsType",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].beatDistributionParam",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].rotationDistributionParam",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].flipRotation",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].brightnessDistributionShouldAffectFirstBaseEvent",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].lightRotationBaseDataList[0].beat",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].lightRotationBaseDataList[0].usePreviousEventRotationValue",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].lightRotationBaseDataList[0].loopsCount",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.lightRotationEventBoxGroups[0].eventBoxes[0].lightRotationBaseDataList[0].rotationDirection",
                    OptionalProperty.NotPresent,
                    NodePresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.vfxEventBoxGroups",
                    OptionalProperty.Present(listOf<BSVfxEventBoxGroup>()),
                    NodeNotPresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`._fxEventsCollection",
                    OptionalProperty.Present(BSFxEventsCollection(OptionalProperty.Present(listOf()), OptionalProperty.Present(listOf()))),
                    NodeNotPresent
                ),
                DefaultConstraintViolation(
                    "_difficultyBeatmapSets[0]._difficultyBeatmaps[0].`Easy.dat`.useNormalEventsAsCompatibleEvents",
                    OptionalProperty.NotPresent,
                    NodePresent
                )
            ),
            ex.constraintViolations
        )
    }
}
